/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpsRouteImport } from './routes/vps'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SponsorshipsRouteImport } from './routes/sponsorships'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MinecraftRouteImport } from './routes/minecraft'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminVpsRouteImport } from './routes/admin.vps'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSponsorshipsRouteImport } from './routes/admin.sponsorships'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMinecraftRouteImport } from './routes/admin.minecraft'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminSponsorshipsApplicationIdRouteImport } from './routes/admin.sponsorships.$applicationId'

const VpsRoute = VpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipsRoute = SponsorshipsRouteImport.update({
  id: '/sponsorships',
  path: '/sponsorships',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MinecraftRoute = MinecraftRouteImport.update({
  id: '/minecraft',
  path: '/minecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVpsRoute = AdminVpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorshipsRoute = AdminSponsorshipsRouteImport.update({
  id: '/sponsorships',
  path: '/sponsorships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinecraftRoute = AdminMinecraftRouteImport.update({
  id: '/minecraft',
  path: '/minecraft',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorshipsApplicationIdRoute =
  AdminSponsorshipsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AdminSponsorshipsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/minecraft': typeof MinecraftRoute
  '/order': typeof OrderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vps': typeof VpsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/minecraft': typeof AdminMinecraftRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsorships': typeof AdminSponsorshipsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vps': typeof AdminVpsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/sponsorships/$applicationId': typeof AdminSponsorshipsApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/minecraft': typeof MinecraftRoute
  '/order': typeof OrderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vps': typeof VpsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/minecraft': typeof AdminMinecraftRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsorships': typeof AdminSponsorshipsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vps': typeof AdminVpsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/sponsorships/$applicationId': typeof AdminSponsorshipsApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/minecraft': typeof MinecraftRoute
  '/order': typeof OrderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vps': typeof VpsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/minecraft': typeof AdminMinecraftRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsorships': typeof AdminSponsorshipsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/vps': typeof AdminVpsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/sponsorships/$applicationId': typeof AdminSponsorshipsApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/builder'
    | '/contact'
    | '/faq'
    | '/games'
    | '/hosting'
    | '/login'
    | '/minecraft'
    | '/order'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/sponsorships'
    | '/status'
    | '/support'
    | '/terms'
    | '/vps'
    | '/admin/faq'
    | '/admin/features'
    | '/admin/games'
    | '/admin/homepage'
    | '/admin/minecraft'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/sponsorships'
    | '/admin/users'
    | '/admin/vps'
    | '/auth/callback'
    | '/admin/sponsorships/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/builder'
    | '/contact'
    | '/faq'
    | '/games'
    | '/hosting'
    | '/login'
    | '/minecraft'
    | '/order'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/sponsorships'
    | '/status'
    | '/support'
    | '/terms'
    | '/vps'
    | '/admin/faq'
    | '/admin/features'
    | '/admin/games'
    | '/admin/homepage'
    | '/admin/minecraft'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/sponsorships'
    | '/admin/users'
    | '/admin/vps'
    | '/auth/callback'
    | '/admin/sponsorships/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/builder'
    | '/contact'
    | '/faq'
    | '/games'
    | '/hosting'
    | '/login'
    | '/minecraft'
    | '/order'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/sponsorships'
    | '/status'
    | '/support'
    | '/terms'
    | '/vps'
    | '/admin/faq'
    | '/admin/features'
    | '/admin/games'
    | '/admin/homepage'
    | '/admin/minecraft'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/settings'
    | '/admin/sponsorships'
    | '/admin/users'
    | '/admin/vps'
    | '/auth/callback'
    | '/admin/sponsorships/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuilderRoute: typeof BuilderRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  HostingRoute: typeof HostingRoute
  LoginRoute: typeof LoginRoute
  MinecraftRoute: typeof MinecraftRoute
  OrderRoute: typeof OrderRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SponsorshipsRoute: typeof SponsorshipsRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VpsRoute: typeof VpsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vps': {
      id: '/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof VpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorships': {
      id: '/sponsorships'
      path: '/sponsorships'
      fullPath: '/sponsorships'
      preLoaderRoute: typeof SponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minecraft': {
      id: '/minecraft'
      path: '/minecraft'
      fullPath: '/minecraft'
      preLoaderRoute: typeof MinecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vps': {
      id: '/admin/vps'
      path: '/vps'
      fullPath: '/admin/vps'
      preLoaderRoute: typeof AdminVpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsorships': {
      id: '/admin/sponsorships'
      path: '/sponsorships'
      fullPath: '/admin/sponsorships'
      preLoaderRoute: typeof AdminSponsorshipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/minecraft': {
      id: '/admin/minecraft'
      path: '/minecraft'
      fullPath: '/admin/minecraft'
      preLoaderRoute: typeof AdminMinecraftRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsorships/$applicationId': {
      id: '/admin/sponsorships/$applicationId'
      path: '/$applicationId'
      fullPath: '/admin/sponsorships/$applicationId'
      preLoaderRoute: typeof AdminSponsorshipsApplicationIdRouteImport
      parentRoute: typeof AdminSponsorshipsRoute
    }
  }
}

interface AdminSponsorshipsRouteChildren {
  AdminSponsorshipsApplicationIdRoute: typeof AdminSponsorshipsApplicationIdRoute
}

const AdminSponsorshipsRouteChildren: AdminSponsorshipsRouteChildren = {
  AdminSponsorshipsApplicationIdRoute: AdminSponsorshipsApplicationIdRoute,
}

const AdminSponsorshipsRouteWithChildren =
  AdminSponsorshipsRoute._addFileChildren(AdminSponsorshipsRouteChildren)

interface AdminRouteChildren {
  AdminFaqRoute: typeof AdminFaqRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMinecraftRoute: typeof AdminMinecraftRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsorshipsRoute: typeof AdminSponsorshipsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVpsRoute: typeof AdminVpsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFaqRoute: AdminFaqRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMinecraftRoute: AdminMinecraftRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsorshipsRoute: AdminSponsorshipsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminVpsRoute: AdminVpsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuilderRoute: BuilderRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  HostingRoute: HostingRoute,
  LoginRoute: LoginRoute,
  MinecraftRoute: MinecraftRoute,
  OrderRoute: OrderRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SponsorshipsRoute: SponsorshipsRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VpsRoute: VpsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
